# -----------------------------------------------------------------------------|
# Advanced data manipulation - data.table ----
# -----------------------------------------------------------------------------|

# FIRST: set the right working directory (.../bootcamp-2018)

# -----------------------------------------------------------------------------|
# data.table basics ----
# -----------------------------------------------------------------------------|

# read in data ----

# import data.table library
library(data.table)
library(lubridate)

data_file <- here::here("data", "generation.csv")

# read in two versions of data, one as a data.frame and one as a data.table
generation_df <- read.csv(data_file, stringsAsFactors = F)
generation_dt <- fread(data_file)

data_file1 <- here::here("data", "imports.csv")
imports$datetime <- as_datetime(imports$datetime)
# compare
View(generation_df)
View(generation_dt)

# directly print the table in the console
generation_df
generation_dt

class(generation_df) # "data.frame"
class(generation_dt) # "data.table" "data.frame" data.table is inheritated from data.frame

str(generation_df)
str(generation_dt)

# -----------------------------------------------------------------------------|
# slicing, column operations, and group by ----
# -----------------------------------------------------------------------------|

# syntax

# data.frame column selection
generation_df[,"small_hydro"]  #it gives you a vector 
select(generation_df, small_hydro) #nicer output as a column(small dataframe)

# data.table column selection
generation_dt[,small_hydro] # !!!No quotes on column names!

# data.frame column selection (multiple)
select(generation_df, datetime, small_hydro)

# data.table column selection (multiple)
# in data table .() = list()
generation_dt[,.(datetime, small_hydro)]
generation_dt[,.(small_hydro)]

# add row filter in i
generation_dt[solar == 0,.(datetime, small_hydro)]
            #row condition #col condition

# try column operations -- find the total hydro generations, arithmetic
generation_dt[,small_hydro + large_hydro]
#if you want it to show as a data table
generation_dt[,.(small_hydro + large_hydro)]

#it results in a new data.table, this means that the all_hydro column won't appear in the generation_dt
generation_dt[,.(datetime, 
                  small_hydro, 
                  large_hydro, 
                 #give the new variable a name
                 all_hydro = small_hydro + large_hydro)]


# try in-place column operations
# this one directly adds all_hydro to generation_dt
generation_dt[,all_hydro := small_hydro + large_hydro]

generation_dt["all_hydro"] <- generation_dt["small_hydro"] + generation_dt["large_hydro"]


# add in by
# how much energy is generated by hydro plants when the output of
# solar plants is zero?

# one way to generate this
generation_dt[solar > 0, solar_on := TRUE] #everything before the comma is the row filter, then create the variable called solar_on
#generation_dt[solar > 0 & solar < 20 , solar_on := TRUE] what you do if multiple filters on
generation_dt[is.na(solar_on), solar_on := FALSE]

# sum by solar_on column
generation_dt[,sum(all_hydro), by = solar_on] #empty before the first comma since we want all rows, so no row filters

# technically, can do this all in one line
generation_dt[,.(sum_hydro = sum(all_hydro)), by = solar > 0] #the .() operator gives sum column a name in the output

# can add as many by groupings as we want
generation_dt[,sum(all_hydro), by = .(solar > 0, wind > 0)]

# Exercise 1
#
# Using `data.table`'s special operator and what you learned about converting
# datetimes in the previous session, convert the `datetime` column to a POSIX
# object. Then, create a new `data.table` that contains the total renewable
# energy generation (solar + wind) by hour and day.
# Hint: you will probably need lubridate's functions `day()` and `hour()`
generation_dt$datetime <- as_datetime(generation_dt$datetime)
generation_dt$day <- day(generation_dt$datetime)
#method2 : generation_dt[, day := day(datetime)]
generation_dt$hour <- hour(generation$datetime)
generation_dt[, .(solar_wind = solar + wind), by = .(day, hour)]
# run answer

# how to delete a column
#generation_dt[,solar_on := NULL]
#generation_dt[,all_hydro := NULL]
generation_dt[,day := NULL]
generation_dt[,hour := NULL]
# -----------------------------------------------------------------------------|
# `data.table` upgrades to other functions ----
# -----------------------------------------------------------------------------|

# from this morning
# imports <- fread(here::here("data", "imports.csv"))
# imports[,datetime := as_datetime(datetime)]

all_generation <- merge(generation_dt, imports, by = "datetime")

all_generation_long <-  melt.data.table(all_generation,
                              id.vars = "datetime", 
                              variable.name = "type")

# now most calculations are much easier
hourly_generation <- all_generation_long[,.(generation = mean(value)), 
                                          by = .(hour(datetime), type)]

# check to see if this makes sense
hourly_generation[type == "solar"]

#number of rows 
hourly_generation[,.N]
all_generation_long[,.I] #useful for the for loop condition
# -----------------------------------------------------------------------------|
# other features ----
# -----------------------------------------------------------------------------|

# keys

# check the current key
key(generation_dt)

# set key
setkey(generation_dt, datetime)
key(generation_dt)

# joins
imports <- data.table(imports)
# this only works if at least one key is set
generation_dt[imports]

# this can also be used to select rows
fewer_imports <- imports[day(datetime) == 3 | day(datetime) == 4]
generation_dt[fewer_imports]

# operations can be performed in the same step as the merge
generation_dt[fewer_imports, sum(small_hydro + large_hydro), by = day(datetime)]


