---
title: "ggplot bootcamp"
author: "Kejin Qian"
date: "9/19/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
source(here::here("data/day3_objects.R"))
```

## Scatterplot from Day1
```{r}
ggplot(data = gapminder07) + 
  geom_point(mapping = aes(x = gdpPercap, y = lifeExp)) + 
  labs(title = "Relationship between life expectancy and GDP per capita in 2007", 
       x = "GDP per capita", y = "Life expectancy")
```
## Exercise 1
```{r}
ggplot(data = gapminder07) +
  geom_point((mapping = aes(x = log(pop), y = log(gdpPercap)))) +
  labs(title = "Relationship between log population and log GDP per capita in 2007",
       x = "log GDP per cap", y = "log Population")
  
```

## Column Chart = Energy Generated over time
```{r}
long_gen %>% 
  group_by(datetime) %>% 
  summarise(output=sum(output)) %>% 
  ggplot() + 
  geom_col(aes(x=datetime, y=output)) + 
  labs(title="Total energy generated, by hour", x="Hour", y="Output (MW)")
```

##Exercise
```{r}
long_gen %>%
  filter(source == 'small_hydro'| source == 'large_hydro') %>%
  group_by(datetime) %>%
  summarise(hydroelectric = sum(output)) %>% 
  ggplot() +
  geom_col(aes(x=datetime, y=hydroelectric)) +
  labs(title = "Total Hydroelectric Power, by hour", x = "Hour", y="Hydroelectric Output")
```

## Line Plots
```{r}
imports %>%
  ggplot() + 
  geom_line(aes(x=datetime, y=imports), size = 1.2, col = 'blue') + 
  labs(title="Energy imports over time", x="Hour", y="Amount imported (MW)")
```

## AREA PLOT
```{r}
generation %>% 
  ggplot() + 
  geom_area(aes(x=datetime, y=wind), fill="darkblue") + 
  labs(title="Hourly wind power generation, Sept 3-9", x="Hour", y="Output (MW)")
```

## BOX PLOT
```{r}
long_gen %>% 
  ggplot() + 
  geom_boxplot(aes(x=source, y=output)) + 
  labs(title="Amount of energy generated by each source, Sept 3-9", x="Source type", y="Output (MW)")
```

##Multiple geoms in one plot
```{r}
generation %>% 
  ggplot() + 
  geom_line(aes(x=datetime, y=large_hydro), col="turquoise3") + 
  geom_smooth(aes(x=datetime, y=large_hydro)) + 
  labs(title="Hydroelectric (large) generation per hour, Sept 3-9", x="Hour", y="Output (MW)")
```

## EXERCISE
```{r}
long_merged_energy %>% 
  group_by(source) %>% 
  summarise(sum_output=sum(output)) %>% 
  ggplot() + 
  geom_col(aes(x=source, y=sum_output), fill = 'darkred') + 
  geom_hline(aes(yintercept = mean(sum_output)), col = 'black') +
  labs(title="Total energy generated, by source", x="Source", y="Output (MW)")
```

## Labels
```{r}
imports %>%
  ggplot() + 
  geom_line(aes(x=datetime, y=imports), col="red") + 
  labs(title="Energy imports over time in California", subtitle="Hourly data from September 3-9, 2018",
       caption="Source: California Energy Commission", x="Hour", y="Amount imported (MW)")
```

## Scale - Datetime
```{r}
imports %>%
  ggplot() + 
  geom_line(aes(x=datetime, y=imports), col="red") + 
  scale_x_datetime(date_labels="%H:%M", date_breaks="12 hours") +
  labs(title="Energy imports over time in California", subtitle="Hourly data from September 3-9, 2018", x="Hour", y="Amount imported (MW)")
```

## Theme layer
```{r}
imports %>%
  ggplot() + geom_line(aes(x=datetime, y=imports), col="red") + 
  scale_x_datetime(date_labels="%H:%M", date_breaks="12 hours") +
  labs(title="Energy imports over time in California", subtitle="Hourly data from September 3-9, 2018", x="Hour", y="Amount imported (MW)") + 
  theme_minimal()
## the difference is the background color
```

## Theme Manual
```{r}
imports %>%
  ggplot() + geom_line(aes(x=datetime, y=imports), col="red") + 
  scale_x_datetime(date_labels="%H:%M", date_breaks="12 hours") +
  labs(title="Energy imports over time in California", subtitle="Hourly data from September 3-9, 2018", x="Hour", y="Amount imported (MW)") + 
  theme(axis.text.x=element_text(angle=45, hjust=1, size=12))
```

## Coordinate System
```{r}
long_gen %>% 
  mutate(date=lubridate::date(datetime)) %>% 
  group_by(date) %>% summarise(output=sum(output)) %>% 
  ggplot() + geom_col(aes(x=date, y=output)) + 
  labs(title="Total energy generated, by day", x="Day", y="Output (MW)")

long_gen %>% 
  mutate(date=lubridate::date(datetime)) %>% 
  group_by(date) %>% summarise(output=sum(output)) %>% 
  ggplot() + geom_col(aes(x=date, y=output)) + 
  labs(title="Total energy generated, by day", x="Day", y="Output (MW)") + 
  coord_flip()
#flip the coordinate system
```

## Visualize Grouped Data
```{r}
long_merged_energy %>%
  ggplot() + 
  geom_line(aes(x=datetime, y=output, group=source, col=source)) + 
  labs(title="Output by energy source over time", subtitle="Hourly data from September 3-9, 2018", x="Date", y="Output (MW)")
```

##Exercise 4: Colors and fill
```{r}
long_merged_energy %>%
  filter(source == 'wind'| source == 'solar' | source == 'geothermal') %>%
  ggplot() +
  geom_line(aes(x=datetime, y= output, group= source, col=source), size = 1.5) +
  scale_color_brewer(palette="Accent", name="Energy source") + 
  labs(title ='Wind vs. Solar vs. Geothermal generation', x = 'Date', y='Output')
```

## Everyday energy per day per source
```{r}
long_merged_energy %>% 
  mutate(date=lubridate::date(datetime)) %>% 
  group_by(date, source) %>% 
  summarize(output=sum(output)) %>% 
  ggplot() + 
  geom_col(aes(x=date, y=output, group=source, fill=source)) + 
  labs(title="Energy use by day", x="Day", y="Output (MW)")

long_merged_energy %>% 
  mutate(date=lubridate::date(datetime)) %>% 
  group_by(date, source) %>% 
  summarize(output=sum(output)) %>% 
  ggplot() + 
  geom_col(aes(x=date, y=output, group=source, fill=source), position = 'dodge') + 
  labs(title="Energy use by day", x="Day", y="Output (MW)")

long_merged_energy %>% 
  mutate(date=lubridate::date(datetime)) %>% 
  group_by(date, source) %>% 
  summarize(output=sum(output)) %>% 
  ggplot() + 
  geom_col(aes(x=date, y=output, group=source, fill=source), position = 'fill') + 
  labs(title="Energy use by day", x="Day", y="Output Propotion (MW)")
## the position fill normalized each bar
```

##Regroup
```{r}
# Prepare data
long_merged_energy_regroup <- long_merged_energy %>%
  rename(type = source) %>% 
  merge(regroup, by = "type") %>% 
  mutate(date=lubridate::date(datetime)) %>% 
  group_by(date, group) %>%
  summarise(output=sum(output))

# Take a look at our prepared data
head(long_merged_energy_regroup)

long_merged_energy_regroup %>% 
  ggplot() + 
  geom_line(aes(x=date, y=output, group=group, col=group, linetype=group), size=0.8) +
  geom_point(aes(x=date, y=output, group=group, shape=group)) + 
  labs(title="Output by source group over time", subtitle="Data collected during September 3-9, 2018", x="Date", y="Output (MW)")

long_merged_energy_regroup %>% 
  ggplot() + 
  geom_line(aes(x=date, y=output, group=group,
                linetype=group), size=1) +
  labs(title="Output by source group over time", subtitle="Data collected during September 3-9, 2018", x="Date", y="Output (MW)")
```

## Color & Size
```{r}
gapminder07 %>% 
  ggplot() + 
  geom_point(aes(x=log(gdpPercap), y=lifeExp, size=pop, col=continent)) + 
  scale_size_continuous(name="Population") + scale_color_discrete(name="Continent") +
  labs(title="Life expectancy as a function of GDP per capita in 2007", x="Logged GDP per capita", y="Life expectancy")
```

##Exercise
```{r}
long_merged_energy %>% 
  mutate(hour=lubridate::hour(datetime)) %>% 
  group_by(hour, source) %>% 
  summarize(output= mean(output)) %>%
  ggplot() + 
  geom_area(aes(x=hour, y=output, fill=factor(source))) + 
  scale_fill_brewer(palette="Set3", name="Source") + 
  labs(title="Average hourly output by source", 
       subtitle="Data collected during September 3-9",
       x="Hour of the day", y="Output (MW)") 
  
```

## Facet
```{r}
long_gen %>% 
  ggplot() + 
  geom_line(aes(x = datetime, y = output)) + 
  facet_wrap(~source) + 
  labs(title="Generation over time, by energy source", subtitle="Hourly data from September 3-9, 2018", x="Hour", y="Output (MW)")

long_gen %>% 
  ggplot() + 
  geom_line(aes(x = datetime, y = output)) + 
  facet_wrap(~source, scales="free") + 
  labs(title="Generation over time, by energy source", subtitle="Hourly data from September 3-9, 2018", x="Hour", y="Output (MW)")
```

##Extercise
```{r}
long_gen %>%
  merge(regroup, by.x ="source", by.y = "type") %>% 
  ggplot() +
  geom_line(aes(x = datetime, y = output, group= group, col= group)) +
  facet_wrap(~source, scales = 'free')+
  labs(title="Generation over time, by energy source", subtitle="Hourly data from   September 3-9, 2018", x="Hour", y="Output (MW)") + 
  theme(legend.position = "bottom")

```

